language: csharp
solution: SmartContracts.NET/Strongforce.sln
sudo: required
dist: xenial
mono: none
dotnet: 2.2

install:
  - dotnet restore SmartContracts.NET/Strongforce.sln

script:
  - dotnet build SmartContracts.NET/Strongforce.sln
  - dotnet test SmartContracts.NET/Strongforce.sln --no-build